name: overlapped_carousel
description: A Flutter package project that is a simple horizontal overlapped_carousel widget.
version: 1.0.2
homepage: https://github.com/delwar36/overlapped_carousel

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: