name: overlapped_carousel
description: A Flutter package project that is a simple horizontal overlapped_carousel widget.
version: 1.0.1
homepage: https://github.com/delwar36/overlapped_carousel

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: